cc_binary(
        name = "multiperiod-binomial",
        srcs = ["main.cc"],
        deps = [
            "//stock:stock-lib",
            "//derivative:derivative-lib",
            "//derivative:europeanCall-lib",
        ],
)
