cc_library(
        name = "stock-lib",
        srcs = ["stock.cc"],
        hdrs = ["stock.h"],
        visibility = [
                "//main:__pkg__",
                "//derivative:__pkg__",
        ],
)